{
 "title": "Muffin dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({level=\"ERROR\"} | json msg=\"msg\", path=\"path\" [$__interval])"
    }
   ]
  },
  {
   "title": "muffin-currency common logs",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({app=\"muffin-currency\"} |= `` | json level=\"level\", path=\"path\" [$__interval])"
    }
   ]
  },
  {
   "title": "Muffin-wallet common logs",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({app=\"muffin-wallet\"} |= `` [$__interval])"
    }
   ]
  },
  {
   "title": "Created Transactions",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({level=\"INFO\"} |= `\"createMuffinTransaction\"` [$__interval])"
    }
   ]
  }
 ]
}